# Generated by Django 5.2.12 on 2026-04-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='passport_images/')),
                ('status', models.CharField(default='auto-extracted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.event')),
                ('passport_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.passportvisitor')),
            ],
            options={
                'unique_together': {('passport_visitor', 'event')},
            },
        ),
    ]
