# Generated by Django 5.2.12 on 2026-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_passportvisitor_passportattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportattendance',
            name='passport_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
