# Generated by Django 5.2.12 on 2026-04-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_passportattendance_passport_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportattendance',
            name='passport_qr_code',
        ),
        migrations.AddField(
            model_name='event',
            name='passport_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='passportvisitor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passportvisitor',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passportvisitor',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passportvisitor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
        migrations.AlterField(
            model_name='passportvisitor',
            name='passport_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
