# Generated by Django 5.2.12 on 2026-04-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_passportattendance_passport_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportvisitor',
            name='extracted_image',
            field=models.ImageField(blank=True, null=True, upload_to='passport_processed/'),
        ),
        migrations.AddField(
            model_name='passportvisitor',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='passportvisitor',
            name='image_quality_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passportvisitor',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passportvisitor',
            name='status',
            field=models.CharField(choices=[('auto-extracted', 'Auto Extracted'), ('manually-corrected', 'Manually Corrected'), ('pending verification', 'Pending Verification')], default='pending verification', max_length=30),
        ),
    ]
