# Generated by Django 5.2.12 on 2026-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_passportvisitor_extracted_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportvisitor',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
