# Generated by Django 5.2.12 on 2026-04-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_attendance_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='attendance',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ipv6_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
    ]
