from django.urls import path
from .views import (
    add_employee,
    analytics_page,
    assignment_attendance_page,
    create_event,
    create_event_assignment,
    dashboard,
    delete_employee,
    delete_event,
    delete_event_assignment,
    delete_passport_attendance,
    delete_staff_attendance,
    delete_visitor_attendance,
    employees_page,
    event_detail,
    events_page,
    export_employees_excel,
    export_event_summary_csv,
    export_assignment_attendance_csv,
    export_staff_attendance_csv,
    export_visitor_attendance_csv,
    export_passport_attendance_csv,
    forgot_password_page,
    import_employees_excel,
    login_page,
    login_user,
    logout_user,
    passport_attendance_page,
    register_manual,
    register_page,
    reset_password_page,
    reset_password_submit,
    send_forgot_password_otp,
    staff_attendance_page,
    submit_assignment_attendance,
    submit_passport_attendance,
    submit_staff_attendance,
    submit_visitor_attendance,
    update_employee,
    update_event,
    update_event_assignment,
    update_passport_attendance,
    update_staff_attendance,
    update_visitor_attendance,
    upload_passport,
    verify_forgot_password_otp,
    visitor_attendance_page,
)

urlpatterns = [
    path('register/manual/', register_manual),
    path('register/', register_page),

    path('login/', login_user),
    path('login-page/', login_page),
    path('logout/', logout_user),

    path('forgot-password/', forgot_password_page),
    path('forgot-password/send-otp/', send_forgot_password_otp),
    path('forgot-password/verify-otp/', verify_forgot_password_otp),
    path('reset-password/', reset_password_page),
    path('reset-password/submit/', reset_password_submit),

    path('dashboard/', dashboard),
    path('analytics/', analytics_page),
    path('dashboard/export-event-summary/<int:id>/', export_event_summary_csv),

    path('employees/', employees_page),
    path('add/', add_employee),
    path('import-excel/', import_employees_excel),
    path('export-excel/', export_employees_excel),
    path('delete/<int:id>/', delete_employee),
    path('update/<int:id>/', update_employee),

    path('events/', events_page),
    path('events/<int:id>/', event_detail),
    path('events/<int:id>/export/assignment/', export_assignment_attendance_csv),
    path('events/<int:id>/export/staff/', export_staff_attendance_csv),
    path('events/<int:id>/export/visitor/', export_visitor_attendance_csv),
    path('events/<int:id>/export/passport/', export_passport_attendance_csv),

    path('event/create/', create_event),
    path('event/update/<int:id>/', update_event),
    path('event/delete/<int:id>/', delete_event),

    path('event-assignment/create/<int:event_id>/', create_event_assignment),
    path('event-assignment/update/<int:id>/', update_event_assignment),
    path('event-assignment/delete/<int:id>/', delete_event_assignment),

    path('assignment-attendance/<int:assignment_id>/', assignment_attendance_page),
    path('assignment-attendance/submit/<int:assignment_id>/', submit_assignment_attendance),

    path('visitor-attendance/<int:event_id>/', visitor_attendance_page),
    path('visitor-attendance/submit/<int:event_id>/', submit_visitor_attendance),
    path('visitor-attendance/update/<int:id>/', update_visitor_attendance),
    path('visitor-attendance/delete/<int:id>/', delete_visitor_attendance),

    path('staff-attendance/<int:event_id>/', staff_attendance_page),
    path('staff-attendance/submit/<int:event_id>/', submit_staff_attendance),
    path('staff-attendance/update/<int:id>/', update_staff_attendance),
    path('staff-attendance/delete/<int:id>/', delete_staff_attendance),

    path('passport-attendance/<int:event_id>/', passport_attendance_page),
    path('passport/upload/', upload_passport),
    path('passport/submit/<int:event_id>/', submit_passport_attendance),
    path('passport-attendance/update/<int:id>/', update_passport_attendance),
    path('passport-attendance/delete/<int:id>/', delete_passport_attendance),
]